import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Link from "next/link";
import BootstrapClient from "./components/BoostrapClient";
import LinkClient from "./components/LinkClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">
        <header className="container-fluid">
          <section className="container SpaceBetween">
            <nav className="navbar navbar-expand-md">
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarNav">
                <ul className="navbar-nav">
                  <li className="nav-item">
                    <LinkClient route={"/"} name="HOME"></LinkClient>
                  </li>
                  <li className="nav-item">
                    <LinkClient
                      route={"/products"}
                      name="PRODUCTS"
                    ></LinkClient>
                  </li>
                </ul>
              </div>
            </nav>
            <article>
              <a href="/">
                <img
                  src="/logo tenco store.png"
                  alt=""
                  style={{ height: "25px", maxHeight: "35px" }}
                />
              </a>
            </article>
            <div>
              <a className="text-decoration-none" href="/login">
                <i className="bi bi-person-circle text-dark fs-2"></i>
              </a>
            </div>
          </section>
        </header>
        {<BootstrapClient />}
        {children}

        <footer
          className="py-5 mt-5 text-center"
          style={{ borderTop: "1px solid white" }}
        >
          <p className="text-light"> All rights reserved @copyrights</p>
        </footer>
      </body>
    </html>
  );
}
